### PR TITLE
Add anchors

### PR DESCRIPTION
**Pull request by bastianjoel**
Closes  #12

### CODE REVIEW

**Comment by bastianjoel** [comment]
Search service supports this now: https://github.com/OpenSlides/openslides-search-service/pull/78

**Review by jsangmeister — APPROVED** [review]
Why not recycle https://github.com/OpenSlides/openslides-meta/pull/12? But it's fine either way

**Comment by jsangmeister** [comment]
Do the changes from https://github.com/OpenSlides/openslides-search-service/pull/78 also have to be included in the AU before we merge this?

**Comment by bastianjoel** [comment]
@ostcar Do you want to adopt the changes?

**Comment by jsangmeister** [comment]
As suspected, does not work:
```
2024/04/05 10:42:47 Can not parse model definition: unmarshalling models.yml: decoding models: field object without type: [1:1] sequence was used where mapping is expected
        >  1 | &languages
               ^
           2 |     - en
           3 |     - de
           4 |     - it
           5 |     
```
@bastianjoel can you port the changes? Or can the code be reused somehow, maybe in the common package which AU and ICC also use?

**Comment by bastianjoel** [comment]
I will port the changes.

**Pull request merged**
